[package]
name = "lsm-kv"
version = "0.1.0"
edition = "2018"

[dependencies]
bit-vec = "0.6.1"
rand = "0.7.3"
page_size = "0.4.2"
mktemp = "0.4.0"
mmap = "0.1.1"
libc = "0.2.67"
threadpool = "1.7.1"
priority-queue = "0.7.0"
bloomfilter = "1.0.2"
getopts = "0.2.21"
str = "0.1.4"
memmap = "0.7.0"